spring:
  datasource:
    url: jdbc:h2:mem:serverdb
  jpa:
    show-sql: true
  data:
    redis:
      host: 39.101.128.195
      port: 6379

logging:
  level:
    com.sakura.server: DEBUG
